"""
Subject code mappings for Sierra College courses.

Maps natural language subject names to official subject codes for better
search accuracy and intent matching.
"""

# Complete mapping of natural language subject names to subject codes (all 62 subjects)
SUBJECT_MAPPING = {
    # Common aliases
    "math": "MATH",
    "psych": "PSYC",
    "cs": "CSCI",
    "theater": "THEA",
    "theatre": "THEA",
    "nursing": "NRSR",
    "esl": "ESL",
    # Full subject names from course data
    "applied art and design": "AAD",
    "administration of justice": "ADMJ",
    "advanced manufacturing": "ADVM",
    "agriculture": "AGRI",
    "allied health": "ALH",
    "anthropology": "ANTH",
    "art history": "ARHI",
    "art": "ART",
    "astronomy": "ASTR",
    "athletics": "ATHL",
    "automotive technology": "AUTO",
    "automotive": "AUTO",
    "building industries": "BI",
    "biological sciences": "BIOL",
    "biology": "BIOL",
    "business": "BUS",
    "chemistry": "CHEM",
    "communication studies": "COMM",
    "communication": "COMM",
    "computer science": "CSCI",
    "deaf studies": "DFST",
    "economics": "ECON",
    "education": "EDU",
    "english": "ENGL",
    "engineering": "ENGR",
    "earth science": "ESCI",
    "english as a second language": "ESL",
    "environmental sciences": "ESS",
    "ethnic studies": "ETHN",
    "fashion": "FASH",
    "fire technology": "FIRE",
    "fire science": "FIRE",
    "french": "FREN",
    "geography": "GEOG",
    "german": "GER",
    "human development and family": "HDEV",
    "health education": "HED",
    "history": "HIST",
    "health sciences": "HSCI",
    "humanities": "HUM",
    "information technology": "IT",
    "italian": "ITAL",
    "japanese": "JPN",
    "kinesiology": "KIN",
    "lgbt studies": "LGBT",
    "mathematics": "MATH",
    "mechatronics": "MECH",
    "music": "MUS",
    "nursing assistant": "NRSA",
    "nursing registered": "NRSR",
    "nutrition and food science": "NUTF",
    "nutrition": "NUTF",
    "personal development": "PDEV",
    "philosophy": "PHIL",
    "photography": "PHOT",
    "physics": "PHYS",
    "political science": "POLS",
    "psychology": "PSYC",
    "recreation management": "RECM",
    "rise": "RISE",
    "skill development": "SKDV",
    "sociology": "SOC",
    "spanish": "SPAN",
    "statistics": "STAT",
    "theatre arts": "THEA",
    "welding technology": "WELD",
    "welding": "WELD",
    "women's studies": "WMST",
}
